export const NEW_LIST_REQUEST = "NEW_LIST_REQUEST";
export const NEW_LIST_SUCCESS = "NEW_LIST_SUCCESS";
export const NEW_LIST_FAIL = "NEW_LIST_FAIL";

export const NEW_DETAIL_REQUEST = " NEW_DETAIL_REQUEST";
export const NEW_DETAIL_SUCCESS = "NEW_DETAIL_SUCCESS";
export const NEW_DETAIL_FAIL = "NEW_DETAIL_FAIL";
